// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnQQzUlMn1IoCx4Y7wvZC_03aPbrhe-AU',
    appId: '1:838576675886:web:52795889ce0669a8cdd3bf',
    messagingSenderId: '838576675886',
    projectId: 'needsbridge-dev',
    authDomain: 'needsbridge-dev.firebaseapp.com',
    storageBucket: 'needsbridge-dev.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0Zci8YeHr-Gqsa2m8pdQzZBmkbQnGvYA',
    appId: '1:838576675886:android:e1cf46cb798822fdcdd3bf',
    messagingSenderId: '838576675886',
    projectId: 'needsbridge-dev',
    storageBucket: 'needsbridge-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBugPT7AYd01grf4VPu50xbZhlPZnbhLJQ',
    appId: '1:838576675886:ios:8a7a72f6311923f8cdd3bf',
    messagingSenderId: '838576675886',
    projectId: 'needsbridge-dev',
    storageBucket: 'needsbridge-dev.firebasestorage.app',
    iosClientId: '838576675886-vfup00qih1prd65mif70kkkg6be4hk6s.apps.googleusercontent.com',
    iosBundleId: 'com.example.needsbridge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBugPT7AYd01grf4VPu50xbZhlPZnbhLJQ',
    appId: '1:838576675886:ios:8a7a72f6311923f8cdd3bf',
    messagingSenderId: '838576675886',
    projectId: 'needsbridge-dev',
    storageBucket: 'needsbridge-dev.firebasestorage.app',
    iosClientId: '838576675886-vfup00qih1prd65mif70kkkg6be4hk6s.apps.googleusercontent.com',
    iosBundleId: 'com.example.needsbridge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnQQzUlMn1IoCx4Y7wvZC_03aPbrhe-AU',
    appId: '1:838576675886:web:ef6f19879460eea8cdd3bf',
    messagingSenderId: '838576675886',
    projectId: 'needsbridge-dev',
    authDomain: 'needsbridge-dev.firebaseapp.com',
    storageBucket: 'needsbridge-dev.firebasestorage.app',
  );

}